### ISSUE TITLE
Import fails in VS 2021 R2

### ISSUE THREAD

**Issue by iamorishi** [ni/niveristand-model-generation-support-for-simulink#4]
When generating the model using R2021b, Model Gen Support 1.1 (or 1.0, I tried both) and importing it into VS 2021 R2, the import fails with the "Error -307703 occurred at SE Dialogs.lvlib:Check model.vi - The specified model is incompatible with Veristand". 

This happens even when compiling a simple model with just one inport connected to an outport in Simulink.

**Comment by CiprianAnton** [comment]
What file did you imported in VeriStand, `.dll`/`.so` or `.vsmodel`? You should import the `.vsmodel` file. Also importing vsmodel through System Explorer is not supported. You should use instead mapping diagram, drop a Simulation Model and specify the path to the `.vsmodel` file.
