### ISSUE TITLE
[Error] gmake: *** No rule to make target

### ISSUE THREAD

**Issue by eddieduy** [ni/niveristand-model-generation-support-for-simulink#7]
I got this kind error during building a Model for NI Linux RT target **gmake: *** No rule to make target**
The below is the error log.
I hope someone can help me.
Thanks in advance.

> === Simulation (Elapsed: 1:04 min) ===
=== Build (Elapsed: 7 sec) ===
    ### Generating code and artifacts to 'Model specific' folder structure
    ### Generating code into build folder: E:\MATLAB\test_veristand_rtw
    ### Invoking Target Language Compiler on test.rtw
    ### Using System Target File: C:\Users\Peritec\AppData\Roaming\MathWorks\MATLAB Add-Ons\Toolboxes\VeriStand Model Generation Support\matlab_support\target\veristand.tlc
            ### Loading TLC function libraries
    ### Initial pass through model to cache user defined code
    .
    ### Caching model source code
    ### Generating TLC interface API.
    ### Writing source file test_capi.c
    ### Writing header file test_capi.h
    ### Writing header file test_types.h
    ### Writing header file test.h
    ### Writing header file rtwtypes.h
    ### Writing header file builtin_typeid_types.h
    ### Writing header file multiword_types.h
    .
    ### Writing source file test.c
    ### Writing header file test_private.h
    ### Writing header file rtmodel.h
    ### Writing source file test_data.c
    ### TLC code generation complete.
    ### Saving binary information cache.
    ### Using toolchain: GCC Compiler for VeriStand NI Linux Real-Time targets | gmake makefile (64-bit Windows)
    ### Creating 'E:\MATLAB\test_veristand_rtw\test.mk' ...
    ### Building 'test': "C:\PROGRA~1\MATLAB\R2022a\bin\win64\gmake"  -f test.mk all
     
    E:\MATLAB\test_veristand_rtw>cd .  
     
    E:\MATLAB\test_veristand_rtw>if "all" == "" ("C:\PROGRA~1\MATLAB\R2022a\bin\win64\gmake"  -f test.mk all )  else ("C:\PROGRA~1\MATLAB\R2022a\bin\win64\gmake"  -f test.mk all )  
    "C:\build\17.0\x64\sysroots\i686-nilrtsdk-mingw32\usr\bin\x86_64-nilrt-linux/x86_64-nilrt-linux-gcc"   -c -m64 -std=c99 -fwrapv -fPIC -fdollars-in-identifiers -DkNIOSLinux=1 --sysroot=C:/build/17.0/x64/sysroots/core2-64-nilrt-linux -O2 -DNDEBUG -DVSMODEL_STEP_SIZE0=1.000000 -DVSMODEL_RT_MDL_INPUTS=test_U -DVSMODEL_RT_MDL_OUTPUTS=test_Y -DVSMODEL_MAJOR_VERSION=1u -DVSMODEL_MINOR_VERSION=2u -DCLASSIC_INTERFACE=0 -DALLOCATIONFCN=0 -DMAT_FILE=0 -DONESTEPFCN=0 -DTERMFCN=1 -DMULTI_INSTANCE_CODE=0 -DINTEGER_CODE=0 -DMT=0  -DTID01EQ=1 -DMODEL=test -DNUMST=2 -DNCSTATES=0 -DHAVESTDIO -DRT -DUSE_RTMODEL  @test_comp.rsp -o"test.obj" "E:/MATLAB/test_veristand_rtw/test.c" 
    "C:\build\17.0\x64\sysroots\i686-nilrtsdk-mingw32\usr\bin\x86_64-nilrt-linux/x86_64-nilrt-linux-gcc"   -c -m64 -std=c99 -fwrapv -fPIC -fdollars-in-identifiers -DkNIOSLinux=1 --sysroot=C:/build/17.0/x64/sysroots/core2-64-nilrt-linux -O2 -DNDEBUG -DVSMODEL_STEP_SIZE0=1.000000 -DVSMODEL_RT_MDL_INPUTS=test_U -DVSMODEL_RT_MDL_OUTPUTS=test_Y -DVSMODEL_MAJOR_VERSION=1u -DVSMODEL_MINOR_VERSION=2u -DCLASSIC_INTERFACE=0 -DALLOCATIONFCN=0 -DMAT_FILE=0 -DONESTEPFCN=0 -DTERMFCN=1 -DMULTI_INSTANCE_CODE=0 -DINTEGER_CODE=0 -DMT=0  -DTID01EQ=1 -DMODEL=test -DNUMST=2 -DNCSTATES=0 -DHAVESTDIO -DRT -DUSE_RTMODEL  @test_comp.rsp -o"test_capi.obj" "E:/MATLAB/test_veristand_rtw/test_capi.c"
    "C:\build\17.0\x64\sysroots\i686-nilrtsdk-mingw32\usr\bin\x86_64-nilrt-linux/x86_64-nilrt-linux-gcc"   -c -m64 -std=c99 -fwrapv -fPIC -fdollars-in-identifiers -DkNIOSLinux=1 --sysroot=C:/build/17.0/x64/sysroots/core2-64-nilrt-linux -O2 -DNDEBUG -DVSMODEL_STEP_SIZE0=1.000000 -DVSMODEL_RT_MDL_INPUTS=test_U -DVSMODEL_RT_MDL_OUTPUTS=test_Y -DVSMODEL_MAJOR_VERSION=1u -DVSMODEL_MINOR_VERSION=2u -DCLASSIC_INTERFACE=0 -DALLOCATIONFCN=0 -DMAT_FILE=0 -DONESTEPFCN=0 -DTERMFCN=1 -DMULTI_INSTANCE_CODE=0 -DINTEGER_CODE=0 -DMT=0  -DTID01EQ=1 -DMODEL=test -DNUMST=2 -DNCSTATES=0 -DHAVESTDIO -DRT -DUSE_RTMODEL  @test_comp.rsp -o"test_data.obj" "E:/MATLAB/test_veristand_rtw/test_data.c"
    gmake: *** No rule to make target `Add-Ons/Toolboxes/VeriStand', needed by `veristand_model_capi.obj'.  Stop.
    E:\MATLAB\test_veristand_rtw>echo The make command returned an error of 2
    The make command returned an error of 2
    E:\MATLAB\test_veristand_rtw>exit /B 1
    Top model targets built:
    
    Model  Action  Rebuild Reason                                    
    =================================================================
    test   Failed  Code generation information file does not exist.  
    
    0 of 1 models built (0 models already up to date)
    Build duration: 0h 0m 7.236s
    Error:Error(s) encountered while building "test"

**Comment by zapplelove** [comment]
I have the same error, did you solve it?

**Comment by zapplelove** [comment]
https://ww2.mathworks.cn/matlabcentral/fileexchange/106420-veristand-model-generation-support?tab=discussions#discussions_2495760

I followed the doc and create a simple model like this：
![](https://www.mathworks.com/matlabcentral/discussions/uploaded_files/16970/image.png)
and I changed the model setting to this：
 ![](https://www.mathworks.com/matlabcentral/discussions/uploaded_files/16975/image.png)
![](https://www.mathworks.com/matlabcentral/discussions/uploaded_files/16980/image.png)
but when use ctrl+B to build the model，I have a error：`gmake: *** No rule to make target 'Add-Ons/Toolboxes/VeriStand', needed by 'veristand_model_capi.obj'.  Stop.`
```
=== Build (Elapsed: 10 sec) ===
    ### Generating code and artifacts to 'Model specific' folder structure
    ### Generating code into build folder: <slx_model_folder>\untitled1_veristand_rtw
    ### Invoking Target Language Compiler on untitled1.rtw
    ### Using System Target File: C:\Users\<username>\AppData\Roaming\MathWorks\MATLAB Add-Ons\Toolboxes\VeriStand Model Generation Support\matlab_support\target\veristand.tlc
            ### Loading TLC function libraries
    ### Initial pass through model to cache user defined code
    ### Caching model source code
    ### Generating TLC interface API.
    ### Writing source file untitled1_capi.c
    ### Writing header file untitled1_capi.h
    ### Writing header file untitled1_types.h
    ### Writing header file untitled1.h
    ### Writing header file rtwtypes.h
    .
    ### Writing header file builtin_typeid_types.h
    ### Writing header file multiword_types.h
    ### Writing source file untitled1.c
    ### Writing header file untitled1_private.h
    ### Writing header file rtmodel.h
    ### Writing source file untitled1_data.c
    .
    ### TLC code generation complete.
    ### Saving binary information cache.
    ### Using toolchain: GCC Compiler for VeriStand Windows targets | gmake makefile (64-bit Windows)
    ### Creating '<slx_model_folder>\untitled1_veristand_rtw\untitled1.mk' ...
    ### Building 'untitled1': "C:\PROGRA~1\MATLAB\R2021b\bin\win64\gmake"  -f untitled1.mk all
     
    <slx_model_folder>\untitled1_veristand_rtw>cd .  
     
    <slx_model_folder>\untitled1_veristand_rtw>if "all" == "" ("C:\PROGRA~1\MATLAB\R2021b\bin\win64\gmake"  -f untitled1.mk all )  else ("C:\PROGRA~1\MATLAB\R2021b\bin\win64\gmake"  -f untitled1.mk all )  
    "C:\PROGRA~3\MATLAB\SupportPackages\R2021b\3P.instrset\mingw_w64.instrset\bin/gcc"   -c -m64 -std=c99 -fwrapv -fPIC -fdollars-in-identifiers -O2 -DNDEBUG -DVSMODEL_STEP_SIZE0=0.010000 -DVSMODEL_RT_MDL_INPUTS=untitled1_U -DVSMODEL_RT_MDL_OUTPUTS=untitled1_Y -DVSMODEL_MAJOR_VERSION=1u -DVSMODEL_MINOR_VERSION=2u -DCLASSIC_INTERFACE=0 -DALLOCATIONFCN=0 -DMAT_FILE=0 -DONESTEPFCN=0 -DTERMFCN=1 -DMULTI_INSTANCE_CODE=0 -DINTEGER_CODE=0 -DMT=0  -DTID01EQ=1 -DMODEL=untitled1 -DNUMST=2 -DNCSTATES=0 -DHAVESTDIO -DRT -DUSE_RTMODEL  @untitled1_comp.rsp -o"untitled1.obj" "D:/Documents/XGWorks/救援机器人/control_Sim/control/untitled1_veristand_rtw/untitled1.c" 
    "C:\PROGRA~3\MATLAB\SupportPackages\R2021b\3P.instrset\mingw_w64.instrset\bin/gcc"   -c -m64 -std=c99 -fwrapv -fPIC -fdollars-in-identifiers -O2 -DNDEBUG -DVSMODEL_STEP_SIZE0=0.010000 -DVSMODEL_RT_MDL_INPUTS=untitled1_U -DVSMODEL_RT_MDL_OUTPUTS=untitled1_Y -DVSMODEL_MAJOR_VERSION=1u -DVSMODEL_MINOR_VERSION=2u -DCLASSIC_INTERFACE=0 -DALLOCATIONFCN=0 -DMAT_FILE=0 -DONESTEPFCN=0 -DTERMFCN=1 -DMULTI_INSTANCE_CODE=0 -DINTEGER_CODE=0 -DMT=0  -DTID01EQ=1 -DMODEL=untitled1 -DNUMST=2 -DNCSTATES=0 -DHAVESTDIO -DRT -DUSE_RTMODEL  @untitled1_comp.rsp -o"untitled1_capi.obj" "D:/Documents/XGWorks/救援机器人/control_Sim/control/untitled1_veristand_rtw/untitled1_capi.c" 
    "C:\PROGRA~3\MATLAB\SupportPackages\R2021b\3P.instrset\mingw_w64.instrset\bin/gcc"   -c -m64 -std=c99 -fwrapv -fPIC -fdollars-in-identifiers -O2 -DNDEBUG -DVSMODEL_STEP_SIZE0=0.010000 -DVSMODEL_RT_MDL_INPUTS=untitled1_U -DVSMODEL_RT_MDL_OUTPUTS=untitled1_Y -DVSMODEL_MAJOR_VERSION=1u -DVSMODEL_MINOR_VERSION=2u -DCLASSIC_INTERFACE=0 -DALLOCATIONFCN=0 -DMAT_FILE=0 -DONESTEPFCN=0 -DTERMFCN=1 -DMULTI_INSTANCE_CODE=0 -DINTEGER_CODE=0 -DMT=0  -DTID01EQ=1 -DMODEL=untitled1 -DNUMST=2 -DNCSTATES=0 -DHAVESTDIO -DRT -DUSE_RTMODEL  @untitled1_comp.rsp -o"untitled1_data.obj" "D:/Documents/XGWorks/救援机器人/control_Sim/control/untitled1_veristand_rtw/untitled1_data.c" 
    gmake: *** No rule to make target `Add-Ons/Toolboxes/VeriStand', needed by `veristand_model_capi.obj'.  Stop.
    <slx_model_folder>\untitled1_veristand_rtw>echo The make command returned an error of 2
    The make command returned an error of 2
    <slx_model_folder>\untitled1_veristand_rtw>exit /B 1
    Top model targets built:
    
    Model      Action  Rebuild Reason                                    
    =====================================================================
    untitled1  Failed  Code generation information file does not exist.  
    
    0 of 1 models built (0 models already up to date)
    Build duration: 0h 0m 9.703s
    Error:Error(s) encountered while building "untitled1"
```
can anyone solve it ?

**Comment by skolthay** [comment]
By any chance, do you also see "NI VeriStand.tlc" in the "system target file browser" window ?
If you do, it means that the system has "Veristand Model Framework" package installed on it. This could be a possible reason for the issue.
You should uninstall the Veristand Model Framework package before using the VeriStand Model Generation Support add-on.

**Comment by zapplelove** [comment]
> By any chance, do you also see "NI VeriStand.tlc" in the "system target file browser" window ? If you do, it means that the system has "Veristand Model Framework" package installed on it. This could be a possible reason for the issue. You should uninstall the Veristand Model Framework package before using the VeriStand Model Generation Support add-on.

actually, I have uninstalled the "Veristand Model Framework" through NI package manager, but the error is still there.

**Comment by zapplelove** [comment]
maybe there is still same rubbish in `regedit` or in windows variable？

**Comment by zapplelove** [comment]
I have uninstalled and reinstalled all the ni packages about three times, and reinstalled the matlab. But the error is still there. @skolthay

**Comment by zapplelove** [comment]
```
=== Build (Elapsed: 7 sec) ===
    ### Generating code and artifacts to 'Model specific' folder structure
    ### Generating code into build folder: <model_path>\untitled1_veristand_rtw
    ### Invoking Target Language Compiler on untitled1.rtw
    ### Using System Target File: C:\Users\zapple\AppData\Roaming\MathWorks\MATLAB Add-Ons\Toolboxes\VeriStand Model Generation Support\matlab_support\target\veristand.tlc
            ### Loading TLC function libraries
    ### Initial pass through model to cache user defined code
    ### Caching model source code
    ### Generating TLC interface API.
    ### Writing source file untitled1_capi.c
    ### Writing header file untitled1_capi.h
    ### Writing header file untitled1_types.h
    ### Writing header file untitled1.h
    ### Writing header file rtwtypes.h
    .
    ### Writing header file builtin_typeid_types.h
    ### Writing header file multiword_types.h
    ### Writing source file untitled1.c
    ### Writing header file untitled1_private.h
    ### Writing header file rtmodel.h
    ### Writing source file untitled1_data.c
    .
    ### TLC code generation complete.
    ### Saving binary information cache.
    ### Using toolchain: Microsoft Visual C++ 2015 v14.0 | nmake (64-bit Windows)
    ### Creating '<model_path>\untitled1_veristand_rtw\untitled1.mk' ...
    ### Building 'untitled1': nmake  -f untitled1.mk all
    <model_path>\untitled1_veristand_rtw>set skipSetupArg=skip_setup_msvc
    <model_path>\untitled1_veristand_rtw>if "skip_setup_msvc" NEQ "skip_setup_msvc" (call "setup_msvc.bat" )
    <model_path>\untitled1_veristand_rtw>cd .
    <model_path>\untitled1_veristand_rtw>if "all" == "" (nmake  -f untitled1.mk all )  else (nmake  -f untitled1.mk all )
    Microsoft (R) 程序维护实用工具 14.00.24234.1 版
    版权所有 (C) Microsoft Corporation。  保留所有权利。
    	cl  -c -nologo -GS -W4 -DWIN32 -D_MT -MT -D_CRT_SECURE_NO_WARNINGS  /O2 /Oy- -DVSMODEL_STEP_SIZE0=0.010000 -DVSMODEL_RT_MDL_INPUTS=untitled1_U -DVSMODEL_RT_MDL_OUTPUTS=untitled1_Y -DVSMODEL_MAJOR_VERSION=1u -DVSMODEL_MINOR_VERSION=2u -DCLASSIC_INTERFACE=0 -DALLOCATIONFCN=0 -DMAT_FILE=0 -DONESTEPFCN=0 -DTERMFCN=1 -DMULTI_INSTANCE_CODE=0 -DINTEGER_CODE=0 -DMT=0  -DTID01EQ=1 -DMODEL=untitled1 -DNUMST=2 -DNCSTATES=0 -DHAVESTDIO -DRT -DUSE_RTMODEL @untitled1_comp.rsp -Fo"untitled1.obj" <model_path>\untitled1_veristand_rtw\untitled1.c
    untitled1.c
    	cl  -c -nologo -GS -W4 -DWIN32 -D_MT -MT -D_CRT_SECURE_NO_WARNINGS  /O2 /Oy- -DVSMODEL_STEP_SIZE0=0.010000 -DVSMODEL_RT_MDL_INPUTS=untitled1_U -DVSMODEL_RT_MDL_OUTPUTS=untitled1_Y -DVSMODEL_MAJOR_VERSION=1u -DVSMODEL_MINOR_VERSION=2u -DCLASSIC_INTERFACE=0 -DALLOCATIONFCN=0 -DMAT_FILE=0 -DONESTEPFCN=0 -DTERMFCN=1 -DMULTI_INSTANCE_CODE=0 -DINTEGER_CODE=0 -DMT=0  -DTID01EQ=1 -DMODEL=untitled1 -DNUMST=2 -DNCSTATES=0 -DHAVESTDIO -DRT -DUSE_RTMODEL @untitled1_comp.rsp -Fo"untitled1_capi.obj" <model_path>\untitled1_veristand_rtw\untitled1_capi.c
    untitled1_capi.c
    	cl  -c -nologo -GS -W4 -DWIN32 -D_MT -MT -D_CRT_SECURE_NO_WARNINGS  /O2 /Oy- -DVSMODEL_STEP_SIZE0=0.010000 -DVSMODEL_RT_MDL_INPUTS=untitled1_U -DVSMODEL_RT_MDL_OUTPUTS=untitled1_Y -DVSMODEL_MAJOR_VERSION=1u -DVSMODEL_MINOR_VERSION=2u -DCLASSIC_INTERFACE=0 -DALLOCATIONFCN=0 -DMAT_FILE=0 -DONESTEPFCN=0 -DTERMFCN=1 -DMULTI_INSTANCE_CODE=0 -DINTEGER_CODE=0 -DMT=0  -DTID01EQ=1 -DMODEL=untitled1 -DNUMST=2 -DNCSTATES=0 -DHAVESTDIO -DRT -DUSE_RTMODEL @untitled1_comp.rsp -Fo"untitled1_data.obj" <model_path>\untitled1_veristand_rtw\untitled1_data.c
    untitled1_data.c
    NMAKE : fatal error U1073: 不知道如何生成“Add-Ons\Toolboxes\VeriStand”
    Stop.
    <model_path>\untitled1_veristand_rtw>echo The make command returned an error of 2
    The make command returned an error of 2
    <model_path>\untitled1_veristand_rtw>exit /B 1
    Top model targets built:
    
    Model      Action  Rebuild Reason                                    
    =====================================================================
    untitled1  Failed  Code generation information file does not exist.  
    
    0 of 1 models built (0 models already up to date)
    Build duration: 0h 0m 7.052s
    Error:Error(s) encountered while building "untitled1"

```

**Comment by skolthay** [comment]
Below articles may have a fix for your problem.

https://in.mathworks.com/matlabcentral/answers/814790-why-do-i-get-the-build-error-no-rule-to-make-target
https://in.mathworks.com/help/rtw/ug/enable-build-process-for-folder-names-with-spaces.html#bu6lx34
